routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();


Route::middleware('auth')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('posts/user/', 'postController@user');
    Route::post('post/like/', 'postController@like');
    Route::delete('post/unlike/{id}', 'postController@unlike');
    Route::get('post/destroy/{id}', 'postController@destroy');
    Route::post('post/{id}/comment', 'postController@comment');
    Route::post('profile/newpost', 'profileController@store2');
    Route::put('comment/{id}/toggleLike', 'CommentController@toggleLike');
    Route::resource('profile', 'profileController');
    Route::resource('post', 'postController');
    Route::resource('follower', 'FollowerController');
    //Route::delete('/follower/{id}','FollowerController@destroy');
    //Route::get('follower/destroy/{id}', 'FollowerController@destroy');
    Route::get('/awal', function () {
        return view('layouts.follower.follower');
    });
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = "posts";
    protected $guarded=[];
  
    public function user()
    {
        return $this->belongsTo('App\User','user_id');
    }

    public function users()
    {
        return $this->belongsToMany('App\User','likes');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment','post_id');
    }
}

app/Http/Controllers/postController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use Illuminate\Http\Request;
use DB;
use App\Post;
use Auth;
use File;
use App\Like;



class postController extends Controller
{
   
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $post = Post::orderByDesc('id')->get();
       
        return view('home', compact('post'));
    }

  
    public function create()
    {
        return view('posts.create');
    }

    public function like(Request $request){
        $user = Post::findorfail($request->idpost);
       $user->users()->attach(Auth::id());


       return redirect('/post');
   
     
     
    }

    public function unlike($id){

       $unlike= Like::findorfail($id);
       $unlike->delete();
       return redirect('/post');
     
     
    }

  
    public function store(Request $request)
    { 
        $request->validate([
        "caption" => "required",
        "quote" => "required",
        "img" => "required|mimes:png,jpg,jpeg"
        ]); //validasi form
    

        $img = $request->img;
        $file_name = time() . "-" . $img->getClientOriginalName();
        Post::create([
            "post" => $request->post,
            'caption' => $request->caption,
            "quote" => $request->quote,
            'img' => $file_name,
            'user_id' => Auth::id()
        ]);

        $img->move('images', $file_name); 

         return redirect('/post')->with('success', 'Post Berhasil dihapus');
        
    }

    
    public function show($id)
    {
        $post = Post::findOrFail($id);
        return view('posts.show', ['post' => $post]);
    }

  
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        return view('posts.edit', ['post' => $post]);
    }

   
    public function update(Request $request, $id)
    {
        $request->validate([
            "caption" => "required",
            "quote" => "required",
            "img" => "mimes:png,jpg,jpeg"
            ]); //validasi form
 

        $post = Post::findorfail($id);
        if ($request->has('img')) {
            $path= "images/";
            File::delete($path . $post->img);
            $img= $request->img;
            $newgambar = time() .'-' . $img->getClientOriginalName();
            $img->move('images' , $newgambar);
            $postdata = [
                "post" => $request->post,
                'caption' => $request->caption,
                "quote" => $request->quote,
                'img' => $newgambar,
                'user_id' => Auth::id()
            ];

        }else{
            $postdata =[
                "post" => $request->post,
                'caption' => $request->caption,
                "quote" => $request->quote,
                'user_id' => Auth::id()
            ];
        }
        
        $post->update($postdata);
        return redirect('/profile')->with('edit','post berhasil di edit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        
        $query= Post::findorfail($id);
        $hapuscomment= Comment::where('post_id',$id)->delete();
       
        $query->users()->sync([]);
  
        $query->delete();



        $path= "images/";
        File::delete($path, $query->img);

        return redirect('/profile')->with('hapus', 'Post Berhasil dihapus');
            
        // return redirect()
        // ->action('postController@user')
        // ->with('success', 'Post Berhasil dihapus');
    }

    /**
     * menampilkan post dari user login
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    
    public function user(Request $request)
    {
        // cari semua posts milik user login
        $posts = Post::where('user_id', '=', Auth::id())->get();
        return view('posts.user', ['posts' => $posts]);
    }

    /**
     * menambahkan comment dari post
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    
    public function comment(Request $request, $id)
    {
        $request->validate([
            'komen' => 'required'
        ]);

        $post = Post::findOrFail($id);
        $post->comments()->create([
            'komen' => $request->input('komen'),
            'user_id' => Auth::id()
        ]);

        return redirect('/post')->with('success', 'komentar berhasil ditambahkan');;
    }
    
}

resources/views/posts/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <div class="card mt-3">

            <!-- Form create Post -->
            <div class="card-body">
                <form method="POST" action="{{ url('post') }}">
                    @csrf
                    {{-- nanti diubah jadi upload file --}}
                    {{-- <div class="form-group row">
                      <label for="staticEmail" class="col-sm-2 col-form-label">Image</label>
                      <div class="col-sm-10">
                        <input type="file" class="form-control-file" name="img">
                      </div>
                    </div> --}}
                    <div class="form-group row">
                        <label for="img" class="col-sm-2 col-form-label">Gambar</label>
                        <div class="col-sm-10">
                        <input type="text" class="form-control" name="img" value="{{ old('img') }}">
                        @error('img')
                            <div id="exampleInputEmail1-error" class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ $message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @enderror
                        </div>
                      </div>
                    <div class="form-group row">
                      <label for="caption" class="col-sm-2 col-form-label">Caption</label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="caption" value="{{ old('caption') }}">
                        @error('caption')
                            <div id="exampleInputEmail1-error" class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ $message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @enderror
                      </div>
                    </div>
                    <div class="form-group row">
                        <label for="quote" class="col-sm-2 col-form-label">Quote</label>
                        <div class="col-sm-10">
                        <input type="text" class="form-control" name="quote" value="{{ old('quote') }}">
                        @error('quote')
                            <div id="exampleInputEmail1-error" class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ $message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputPassword" class="col-sm-2 col-form-label">Teks</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" aria-label="With textarea" name="post">{{ old('post') }}</textarea>
                            @error('post')
                                <div id="exampleInputEmail1-error" class="alert alert-danger alert-dismissible fade show" role="alert">
                                    {{ $message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @enderror
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>

        </div>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
      <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-2  mx-auto  ">
                            <img src="{{asset('images/'. $post->img)}}" class="ml-2" style="width: 150px;height:150px;background-size:cover;margin-top:200px;" alt="">
                        </div>
                        <div class="col-lg-10">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Ubah data post kamu</h1>
                                </div>
                                <form action="{{route('post.update',$post->id)}}" method="POST" enctype="multipart/form-data">
                                  @csrf
                                  @method('put')
                                  <div class="row">
                                      <div class="col-6">
                                      
                                              <div class="form-group">
                                      
                                                  <div class="preview_holder">
                                                      <div id="preview2">
                                                      <img src="" id="preview_img" class="preview_img" height="200" width="200" />
                                                      <span id="preview_text" class="preview_text"></span>
                                                      </div>
                                                  </div>
                                                  <!-- Input Markup -->
                                                  <input type="file" id="default-file" name="img" hidden="hidden" />
                                          
                                                  <!-- Button Markup -->
                                                  <button id="custom-btn" type="button"  class="btns mt-2 mx-auto btn-sm" >
                                                  Upload gambar
                                                  </button>
                                                  <br>
                                          
                                                  <!-- Choose File TEXT Markup -->
                                                  <span id="custom-space" style="color: black;"> <strong> No</strong> File, Selected!😭</span>
                                              
                                              </div>
                                        
                                      
                                      </div>
                                      <div class="col-6">
                                          <div class="form-group ">
                                              <input type="text" class="form-control form-control-user form-control @error('caption') is-invalid @enderror" 
                                              name="caption" value="{{ old('caption')  }}{{$post->caption}}" required autocomplete="caption" placeholder="caption" autofocus
                                                  >
                                          </div>
                                          <div class="form-group ">
                                              <input type="text" class="form-control form-control-user form-control @error('quote') is-invalid @enderror" 
                                              name="quote" value="{{ old('quote') }}{{$post->quote}}" required autocomplete="quote" placeholder="quote" autofocus
                                                  >
                                          </div>
                                          <div class="form-group">
                                              <textarea class="form-control  form-control-user"
                                                  id="exampleInputPassword" name="post" rows="9" >{{$post->post}}</textarea>
                                          </div>
                                          <div class="row">
                                            <div class="col-6">
                                              <a href="{{route('profile.index')}}" class=" btn btn-secondary btns mx-auto ">Kembali</a>
                                            </div>
                                            <div class="col-6">
                                              <button type="submit" class="btn btn-primary btns mx-auto ">Update post</button>
                                            </div>
                                          </div>
                                          
                                         
                                      </div>
                                  </div>
                              </form>
                        
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
    </div>
@endsection


@push('uploads')
  <script>

    // Grabbing Elements and Storing in Variables
    const defaultFile = document.getElementById("default-file");
const customBtn = document.getElementById("custom-btn");
const customSpace = document.getElementById("custom-space");
customBtn.addEventListener("click", function () {
  defaultFile.click();
});

// File Upload
defaultFile.addEventListener("change", function () {
  //  Format Selected File Text
  if (defaultFile.value) {
    customSpace.innerHTML =
      defaultFile.value.match(/[\/\\]([\w\d\s\.\-\(\)]+)$/)[1] + "🔥";
  } else {
    customSpace.innerHTML = "No File, Selected!😭";
  }

  // Image Preview
  const files = defaultFile.files[0]; //files[0] - For getting first file
  //   console.log(files);

  if (files) {
    // Showing Image and Hiding "Image Preview" Text
    preview_img.style.display = "block";
    preview_text.style.display = "none";
    //Read File
    const fileReader = new FileReader();

    fileReader.addEventListener("load", function () {
      // convert image to base64 encoded string
      preview_img.setAttribute("src", this.result);
      console.log(this.result);
    });
    fileReader.readAsDataURL(files);
  }
});
    </script>
@endpush

resources/views/posts/show.blade.php
@extends('layouts.master')


@section('content')
<div class="container mt-3">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <!-- User Section-->
                <div class="card-body">
                <div class="row">
                    <div class="col-1">
                    <img src="{{asset('template/img/login.jpg')}}" height="40" class="rounded-circle" alt="">
                    </div>
                    <div class="col-8  ml-3">
                        <a href=""  class="link-dark">{{$post->user->name}}</a>
                        <br>
                        
                    </div>
                    <div class="col-3 "></div>
                </div>
                    
                </div>

                <!-- Post Section-->
                <img class="card-img-top" src="{{asset('template/img/login.jpg')}}"  height="400" style="background-size: cover; margin-top: -20px;" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title"><a href="{{ url('post/'.$post->id) }}">{{ $post->caption }}</a></h5>
                    <p class="card-text">{{ $post->quote }}</p>
                    <p class="card-text">{{ $post->post }}</p>
                    <div class="row mt-2">
                    <div class="col-4 ">
                        <p class="text-center">14 like</p> 
                    </div>
                    <div class="col-4">
                        <p class="text-center">14 like</p> 
                    </div>
                    <div class="col-4">
                        <p class="text-center">14 like</p> 
                    </div>
                    </div>
                </div>
                
            </div><!-- end card -->
        </div>
        <div class="col-3"></div>
</div>
@endsection

resources/views/posts/user.blade.php
@extends('layouts.master')


@section('content')
    
<div class="container mt-3">
  <!-- success message -->
  @if (session('success'))
    <div id="exampleInputEmail1-error" class="alert alert-success alert-dismissible fade show" role="alert">
      {{ session('success') }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
    </div>
  @endif

  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <h1>Your Posts</h1>
      <a href="/post/create" class="btn btn-primary mb-1">Buat Post</a>

      @forelse ($posts as $post)
        <div class="card">
          <!-- User Section-->
          <div class="card-body">
            <div class="row">
              <div class="col-1">
                <img src="{{asset('template/img/login.jpg')}}" height="40" class="rounded-circle" alt="">
              </div>
              <div class="col-8  ml-3">
                  <a href=""  class="link-dark">{{$post->user->name}}</a>
                  <br>
                  
              </div>
              <div class="col-3 "></div>
            </div>
              
          </div>

          <!-- Post Section-->
          <img class="card-img-top" src="{{asset('template/img/login.jpg')}}"  height="400" style="background-size: cover; margin-top: -20px;" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"><a href="{{ url('post/'.$post->id) }}">{{ $post->caption }}</a></h5>
              <p class="card-text">{{ $post->quote }}</p>
              <p class="card-text">{{ $post->post }}</p>
              <div class="row mt-2">
                <div class="col-6 ">
                    <p class="text-center"><a href="{{ url('post/'.$post->id.'/edit/') }}">Edit</a></p> 
                </div>
                <div class="col-6">
                  <form action="{{ url('post/'.$post->id.'/') }}" method="POST">
                    @method('DELETE')
                    @csrf
                    <button class="text-center" style="background: none;color: #224abe;border: none;padding: 0;font: inherit;cursor: pointer;outline: inherit;" type="submit">
                      Delete
                    </button> 
                  </form>
                </div>
              </div>
            </div>
          
        </div><!-- end card -->
      @empty
          <h3>Post tidak ditemukan</h3>
      @endforelse

      </div>
      <div class="col-4">

      </div>
    </div>
</div>
@endsection